import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  route("onboarding", "routes/onboarding.tsx"),
  route("onboarding/client-discovery", "routes/client-discovery-onboarding.tsx"),
  route("new-landing", "routes/new-landing.tsx"),
  route("lawyers", "routes/lawyers.tsx"),
  index("routes/home.tsx"),
  route("services", "routes/services.tsx"),
  route("website", "routes/website.tsx"),
  route("webdesign", "routes/webdesign.tsx"),
  route("seo", "routes/seo.tsx"),
  route("google-ads", "routes/google-ads.tsx"),
  route("services/website", "routes/services-website.tsx"),
  route("services/seo", "routes/services-seo.tsx"),
  route("services/google-ads", "routes/services-google-ads.tsx"),
  route("leistungen/webdesign", "routes/leistungen-webdesign.tsx"),
  route("leistungen/seo", "routes/leistungen-seo.tsx"),
  route("leistungen/google-ads", "routes/leistungen-google-ads.tsx"),
  route("tr/*", "routes/legacy-turkish-redirect.tsx"),
  route("datenschutz", "routes/datenschutz.tsx"),
  route("impressum", "routes/impressum.tsx"),
  route("blog", "routes/blog-list.tsx"),
  route("blog/:slug", "routes/blog-post.tsx"),
  route("admin/login", "routes/admin-login.tsx"),
  route("admin", "routes/admin.tsx", [
    index("routes/admin-dashboard.tsx"),
    route("projects", "routes/admin-projects.tsx"),
    route("jobs", "routes/admin-jobs.tsx"),
    route("jobs/:id", "routes/admin-job-detail.tsx"),
  ]),
] satisfies RouteConfig;
