// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/onboarding" | "/blog" | "/blog/:slug";
  };
  "routes/onboarding.tsx": {
    id: "routes/onboarding";
    page: "/onboarding";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/blog-list.tsx": {
    id: "routes/blog-list";
    page: "/blog";
  };
  "routes/blog-post.tsx": {
    id: "routes/blog-post";
    page: "/blog/:slug";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/onboarding": typeof import("./app/routes/onboarding.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/blog-list": typeof import("./app/routes/blog-list.tsx");
  "routes/blog-post": typeof import("./app/routes/blog-post.tsx");
};