// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/onboarding/client-discovery": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/website": {
    params: {};
  };
  "/webdesign": {
    params: {};
  };
  "/seo": {
    params: {};
  };
  "/google-ads": {
    params: {};
  };
  "/services/website": {
    params: {};
  };
  "/services/seo": {
    params: {};
  };
  "/services/google-ads": {
    params: {};
  };
  "/leistungen/webdesign": {
    params: {};
  };
  "/leistungen/seo": {
    params: {};
  };
  "/leistungen/google-ads": {
    params: {};
  };
  "/datenschutz": {
    params: {};
  };
  "/impressum": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/admin/login": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/projects": {
    params: {};
  };
  "/admin/jobs": {
    params: {};
  };
  "/admin/jobs/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/onboarding" | "/onboarding/client-discovery" | "/services" | "/website" | "/webdesign" | "/seo" | "/google-ads" | "/services/website" | "/services/seo" | "/services/google-ads" | "/leistungen/webdesign" | "/leistungen/seo" | "/leistungen/google-ads" | "/datenschutz" | "/impressum" | "/blog" | "/blog/:slug" | "/admin/login" | "/admin" | "/admin/projects" | "/admin/jobs" | "/admin/jobs/:id";
  };
  "routes/onboarding.tsx": {
    id: "routes/onboarding";
    page: "/onboarding";
  };
  "routes/client-discovery-onboarding.tsx": {
    id: "routes/client-discovery-onboarding";
    page: "/onboarding/client-discovery";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/services.tsx": {
    id: "routes/services";
    page: "/services";
  };
  "routes/website.tsx": {
    id: "routes/website";
    page: "/website";
  };
  "routes/webdesign.tsx": {
    id: "routes/webdesign";
    page: "/webdesign";
  };
  "routes/seo.tsx": {
    id: "routes/seo";
    page: "/seo";
  };
  "routes/google-ads.tsx": {
    id: "routes/google-ads";
    page: "/google-ads";
  };
  "routes/services-website.tsx": {
    id: "routes/services-website";
    page: "/services/website";
  };
  "routes/services-seo.tsx": {
    id: "routes/services-seo";
    page: "/services/seo";
  };
  "routes/services-google-ads.tsx": {
    id: "routes/services-google-ads";
    page: "/services/google-ads";
  };
  "routes/leistungen-webdesign.tsx": {
    id: "routes/leistungen-webdesign";
    page: "/leistungen/webdesign";
  };
  "routes/leistungen-seo.tsx": {
    id: "routes/leistungen-seo";
    page: "/leistungen/seo";
  };
  "routes/leistungen-google-ads.tsx": {
    id: "routes/leistungen-google-ads";
    page: "/leistungen/google-ads";
  };
  "routes/datenschutz.tsx": {
    id: "routes/datenschutz";
    page: "/datenschutz";
  };
  "routes/impressum.tsx": {
    id: "routes/impressum";
    page: "/impressum";
  };
  "routes/blog-list.tsx": {
    id: "routes/blog-list";
    page: "/blog";
  };
  "routes/blog-post.tsx": {
    id: "routes/blog-post";
    page: "/blog/:slug";
  };
  "routes/admin-login.tsx": {
    id: "routes/admin-login";
    page: "/admin/login";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin" | "/admin/projects" | "/admin/jobs" | "/admin/jobs/:id";
  };
  "routes/admin-dashboard.tsx": {
    id: "routes/admin-dashboard";
    page: "/admin";
  };
  "routes/admin-projects.tsx": {
    id: "routes/admin-projects";
    page: "/admin/projects";
  };
  "routes/admin-jobs.tsx": {
    id: "routes/admin-jobs";
    page: "/admin/jobs";
  };
  "routes/admin-job-detail.tsx": {
    id: "routes/admin-job-detail";
    page: "/admin/jobs/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/onboarding": typeof import("./app/routes/onboarding.tsx");
  "routes/client-discovery-onboarding": typeof import("./app/routes/client-discovery-onboarding.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/services": typeof import("./app/routes/services.tsx");
  "routes/website": typeof import("./app/routes/website.tsx");
  "routes/webdesign": typeof import("./app/routes/webdesign.tsx");
  "routes/seo": typeof import("./app/routes/seo.tsx");
  "routes/google-ads": typeof import("./app/routes/google-ads.tsx");
  "routes/services-website": typeof import("./app/routes/services-website.tsx");
  "routes/services-seo": typeof import("./app/routes/services-seo.tsx");
  "routes/services-google-ads": typeof import("./app/routes/services-google-ads.tsx");
  "routes/leistungen-webdesign": typeof import("./app/routes/leistungen-webdesign.tsx");
  "routes/leistungen-seo": typeof import("./app/routes/leistungen-seo.tsx");
  "routes/leistungen-google-ads": typeof import("./app/routes/leistungen-google-ads.tsx");
  "routes/datenschutz": typeof import("./app/routes/datenschutz.tsx");
  "routes/impressum": typeof import("./app/routes/impressum.tsx");
  "routes/blog-list": typeof import("./app/routes/blog-list.tsx");
  "routes/blog-post": typeof import("./app/routes/blog-post.tsx");
  "routes/admin-login": typeof import("./app/routes/admin-login.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/admin-dashboard": typeof import("./app/routes/admin-dashboard.tsx");
  "routes/admin-projects": typeof import("./app/routes/admin-projects.tsx");
  "routes/admin-jobs": typeof import("./app/routes/admin-jobs.tsx");
  "routes/admin-job-detail": typeof import("./app/routes/admin-job-detail.tsx");
};